repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "aab412d509121cb5f7533134b7e67f9fab59c682"  # frozen: v0.16.4
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "7ff8d35ae36a7d2b968f2f90b4c723e292e594ee"  # frozen: v2.3.1
  hooks:
    - id: mypy
      files: src
      args: []

- repo: https://github.com/abravalheri/validate-pyproject
  rev: "17e12779811926f000bdfa1795f9e3735dd71ac3"  # frozen: 0.26
  hooks:
    - id: validate-pyproject
      additional_dependencies: ["validate-pyproject-schema-store[all]>=2024.10.21"]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: "c4654a7e007c9619a5eb63c39a456572a0fa1851"  # frozen: 0.38.0
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
    - id: check-readthedocs

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
  hooks:
  - id: zizmor
    files: "^\\.github"
