version: 2

references:

  ci_steps: &ci_steps
    working_directory: /work
    steps:
      - checkout
      - run:
          name: Run CI
          command: |
            #
            # Set UPLOAD_SDIST environment variable
            #
            export UPLOAD_SDIST=$(echo ${CIRCLE_JOB} | cut -d"_" -f3)
            echo "UPLOAD_SDIST [${UPLOAD_SDIST}]"
            #
            # Run CI
            #
            export MANYLINUX_PYTHON=$(echo ${CIRCLE_JOB} | cut -d"_" -f2)
            echo "MANYLINUX_PYTHON [${MANYLINUX_PYTHON}]"
            /opt/python/${MANYLINUX_PYTHON}/bin/pip install scikit-ci
            /opt/python/${MANYLINUX_PYTHON}/bin/ci
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  x64_build_job: &x64_build_job
    docker:
      - image: dockcross/manylinux-x64
    <<: *ci_steps

  x86_build_job: &x86_build_job
    docker:
      - image: dockcross/manylinux-x86
    <<: *ci_steps

  no_filters: &no_filters
    filters:
      tags:
        only: /.*/

jobs:

  # x64
  manylinux-x64_cp27-cp27m:
    <<: *x64_build_job
  manylinux-x64_cp27-cp27mu:
    <<: *x64_build_job
  manylinux-x64_cp34-cp34m:
    <<: *x64_build_job
  manylinux-x64_cp35-cp35m:
    <<: *x64_build_job
  manylinux-x64_cp36-cp36m:
    <<: *x64_build_job
  manylinux-x64_cp37-cp37m_upload-sdist:
    <<: *x64_build_job

  # x86
  manylinux-x86_cp27-cp27m:
    <<: *x86_build_job
  manylinux-x86_cp27-cp27mu:
    <<: *x86_build_job
  manylinux-x86_cp34-cp34m:
    <<: *x86_build_job
  manylinux-x86_cp35-cp35m:
    <<: *x86_build_job
  manylinux-x86_cp36-cp36m:
    <<: *x86_build_job
  manylinux-x86_cp37-cp37m:
    <<: *x86_build_job

  deploy-master:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy master
          command: |
            echo "Deploy master (not implemented)"

  deploy-release:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy release
          command: |
            echo "Deploy release"
            python -m venv ../venv
            . ../venv/bin/activate
            pip install twine
            ls dist
            twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # x64
      - manylinux-x64_cp27-cp27m:
          <<: *no_filters
      - manylinux-x64_cp27-cp27mu:
          <<: *no_filters
      - manylinux-x64_cp34-cp34m:
          <<: *no_filters
      - manylinux-x64_cp35-cp35m:
          <<: *no_filters
      - manylinux-x64_cp36-cp36m:
          <<: *no_filters
      - manylinux-x64_cp37-cp37m_upload-sdist:
          <<: *no_filters
      # x86
      - manylinux-x86_cp27-cp27m:
          <<: *no_filters
      - manylinux-x86_cp27-cp27mu:
          <<: *no_filters
      - manylinux-x86_cp34-cp34m:
          <<: *no_filters
      - manylinux-x86_cp35-cp35m:
          <<: *no_filters
      - manylinux-x86_cp36-cp36m:
          <<: *no_filters
      - manylinux-x86_cp37-cp37m:
          <<: *no_filters

      - deploy-master:
          requires:
            # x64
            - manylinux-x64_cp27-cp27m
            - manylinux-x64_cp27-cp27mu
            - manylinux-x64_cp34-cp34m
            - manylinux-x64_cp35-cp35m
            - manylinux-x64_cp36-cp36m
            - manylinux-x64_cp37-cp37m_upload-sdist
            # x86
            - manylinux-x86_cp27-cp27m
            - manylinux-x86_cp27-cp27mu
            - manylinux-x86_cp34-cp34m
            - manylinux-x86_cp35-cp35m
            - manylinux-x86_cp36-cp36m
            - manylinux-x86_cp37-cp37m
          filters:
            branches:
              only: master
      - deploy-release:
          requires:
            # x64
            - manylinux-x64_cp27-cp27m
            - manylinux-x64_cp27-cp27mu
            - manylinux-x64_cp34-cp34m
            - manylinux-x64_cp35-cp35m
            - manylinux-x64_cp36-cp36m
            - manylinux-x64_cp37-cp37m_upload-sdist
            # x86
            - manylinux-x86_cp27-cp27m
            - manylinux-x86_cp27-cp27mu
            - manylinux-x86_cp34-cp34m
            - manylinux-x86_cp35-cp35m
            - manylinux-x86_cp36-cp36m
            - manylinux-x86_cp37-cp37m
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/
            branches:
              ignore: /.*/

